import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadConfig, resolveCocopitHome } from "../config";
import type { Router } from "../http/router";
import type { IndexScheduler, ScanSource } from "../indexer/scheduler";
import { detectProfile, loginCommand, shellQuote } from "../profiles/detect";
import { fetchProfileQuota } from "../profiles/quota";
import {
  createProfile,
  deleteProfile,
  loadProfiles,
  updateProfile,
  type CcProfile,
  type CcProfileApi,
} from "../profiles/registry";

function maskSecret(secret: string): string {
  return `****${secret.slice(-4)}`;
}

/** API view of a profile: secrets masked, detection/login helpers attached. */
function toView(profile: CcProfile): Record<string, unknown> {
  const view: Record<string, unknown> = { ...profile };
  if (profile.api) {
    view.api = { ...profile.api, secret: maskSecret(profile.api.secret) };
  }
  if (profile.kind === "subscription") {
    view.loginCommand = loginCommand(profile);
  }
  view.detection = detectProfile(profile);
  return view;
}

function currentProfileScript(profile: CcProfile, configDir: string | null): string {
  const lines = ["# generated by cocopit — source this from your shell rc (optional)"];
  if (profile.product === "codex") {
    lines.push(configDir ? `export CODEX_HOME=${shellQuote(configDir)}` : "unset CODEX_HOME");
    return lines.join("\n") + "\n";
  }
  if (configDir) {
    lines.push(`export CLAUDE_CONFIG_DIR=${shellQuote(configDir)}`);
  } else {
    lines.push("unset CLAUDE_CONFIG_DIR");
  }
  if (profile.kind === "api" && profile.api) {
    const { baseUrl, model, smallFastModel, authKind, secret } = profile.api;
    if (baseUrl) lines.push(`export ANTHROPIC_BASE_URL=${shellQuote(baseUrl)}`);
    lines.push(
      authKind === "api_key"
        ? `export ANTHROPIC_API_KEY=${shellQuote(secret)}`
        : `export ANTHROPIC_AUTH_TOKEN=${shellQuote(secret)}`,
    );
    if (model) lines.push(`export ANTHROPIC_MODEL=${shellQuote(model)}`);
    if (smallFastModel) lines.push(`export ANTHROPIC_SMALL_FAST_MODEL=${shellQuote(smallFastModel)}`);
  }
  for (const [key, value] of Object.entries(profile.extraEnv ?? {})) {
    lines.push(`export ${key}=${shellQuote(value)}`);
  }
  return lines.join("\n") + "\n";
}

export function registerProfileRoutes(
  router: Router,
  scheduler: IndexScheduler,
  sources: () => ScanSource[],
): void {
  router.register("GET", "/api/profiles", (req) => {
    const product = new URL(req.url).searchParams.get("product");
    let profiles = loadProfiles();
    if (product === "codex") {
      profiles = profiles.filter((p) => p.product === "codex");
      // the machine's own ~/.codex is the implicit default Codex account —
      // synthesized as a view, never written to the registry
      const codexDefault: CcProfile = {
        id: "default",
        name: "默认账号",
        kind: "subscription",
        product: "codex",
        configDir: loadConfig().codexDir,
      };
      return Response.json({ profiles: [toView(codexDefault), ...profiles.map(toView)] });
    }
    if (product === "claude" || product === null) {
      profiles = profiles.filter((p) => p.product !== "codex");
    }
    return Response.json({ profiles: profiles.map(toView) });
  });

  router.register("POST", "/api/profiles", async (req) => {
    let body: { name?: string; kind?: string; color?: string; api?: CcProfileApi; product?: string };
    try {
      body = (await req.json()) as typeof body;
    } catch {
      return Response.json({ error: "invalid JSON body" }, { status: 400 });
    }
    if (!body.name || (body.kind !== "subscription" && body.kind !== "api")) {
      return Response.json({ error: "name and kind ('subscription'|'api') are required" }, { status: 400 });
    }
    if (body.kind === "api" && !body.api?.secret) {
      return Response.json({ error: "api profiles need api.secret" }, { status: 400 });
    }
    if (body.product === "codex" && body.kind === "api") {
      return Response.json(
        { error: "Codex API 接入请使用其 config.toml 的 model_providers;此处仅支持登录账号" },
        { status: 400 },
      );
    }
    const profile = createProfile({
      name: body.name,
      kind: body.kind,
      product: body.product === "codex" ? "codex" : undefined,
      color: body.color,
      api: body.api,
    });
    // pick the new profile's dir up in the index right away
    void scheduler.runScan(sources());
    return Response.json(toView(profile), { status: 201 });
  });

  router.register("PATCH", "/api/profiles/:id", async (req, params) => {
    let body: Partial<CcProfile>;
    try {
      body = (await req.json()) as Partial<CcProfile>;
    } catch {
      return Response.json({ error: "invalid JSON body" }, { status: 400 });
    }
    try {
      const existing = loadProfiles().find((p) => p.id === params.id);
      if (!existing) return Response.json({ error: "not found" }, { status: 404 });
      // a masked secret means "keep the stored one"
      if (body.api && existing.api && body.api.secret?.startsWith("****")) {
        body.api = { ...body.api, secret: existing.api.secret };
      }
      // identity fields are fixed: repointing configDir would silently make a
      // profile read another account's data
      const patch: Partial<CcProfile> = {};
      for (const key of ["name", "color", "api", "extraEnv", "lastDetected"] as const) {
        if (key in body) (patch as Record<string, unknown>)[key] = body[key];
      }
      const updated = updateProfile(params.id!, patch);
      return Response.json(toView(updated));
    } catch (err) {
      return Response.json({ error: (err as Error).message }, { status: 400 });
    }
  });

  router.register("DELETE", "/api/profiles/:id", (_req, params) => {
    try {
      deleteProfile(params.id!);
      return Response.json({ deleted: params.id });
    } catch (err) {
      return Response.json({ error: (err as Error).message }, { status: 400 });
    }
  });

  router.register("GET", "/api/profiles/:id/detect", (_req, params) => {
    const profile = loadProfiles().find((p) => p.id === params.id);
    if (!profile) return Response.json({ error: "not found" }, { status: 404 });
    const detection = detectProfile(profile);
    if (detection.loggedIn && detection.email) {
      updateProfile(profile.id, {
        lastDetected: { email: detection.email, orgName: detection.orgName, at: Date.now() },
      });
    }
    return Response.json(detection);
  });

  // Quota percentages only — the OAuth token this reads stays inside the
  // process and is never part of the response. See profiles/quota.ts.
  router.register("GET", "/api/profiles/:id/quota", async (_req, params) => {
    const profile = loadProfiles().find((p) => p.id === params.id);
    if (!profile) return Response.json({ error: "not found" }, { status: 404 });
    return Response.json(await fetchProfileQuota(profile));
  });

  router.register("GET", "/api/profiles/:id/login-command", (_req, params) => {
    const profile = loadProfiles().find((p) => p.id === params.id);
    if (!profile) return Response.json({ error: "not found" }, { status: 404 });
    return Response.json({ command: loginCommand(profile) });
  });

  router.register("POST", "/api/profiles/:id/activate", (_req, params) => {
    const profile = loadProfiles().find((p) => p.id === params.id);
    if (!profile) return Response.json({ error: "not found" }, { status: 404 });
    const scriptPath = join(resolveCocopitHome(), "current-profile.sh");
    writeFileSync(scriptPath, currentProfileScript(profile, profile.configDir), { mode: 0o600 });
    return Response.json({
      activated: profile.id,
      scriptPath,
      note: "仅对之后 source 该脚本的新终端生效;已开终端不受影响",
    });
  });
}
